#yaml-language-server: $schema=https://json.schemastore.org/taskfile
version: "3"
tasks:
  default:
    cmds:
      - task: build:cosmes
      - task: build:shoelace

  build:cosmes:
    dir: packages/cosmes
    cmds:
      - devbox run build

  build:shoelace:
    dir: packages/shoelace
    cmds:
      - devbox run build

  templ-gen:
    cmds:
      - templ generate
    silent: true

  nebula:build:
    dir: .
    cmds:
      - devbox run build
    silent: true

  nebula:publish:
    dir: .
    cmds:
      - devbox run publish
    silent: true

  nebula:bump:
    dir: .
    internal: true
    cmds:
      - devbox run bump
      - git add .
      - git commit -m "(chore) update build version [skip ci]"
      - git push
