#yaml-language-server: $schema=https://json.schemastore.org/taskfile
version: "3"
silent: true
tasks:
  default:
    cmds:
      - task: gen
      - task: build

  test:
    cmds:
      - go test -v ./...

  build:
    cmds:
      - task: build:cosmes
      - task: build:shoelace
      - task: build:example

  dev:
    cmds:
      - air

  gen:templ:
    aliases:
      - gen
      - g
    sources:
      - "**/*.templ"
    generates:
      - "**/_templ.go"
    cmds:
      - templ generate
      - gum log --level info --time kitchen "[UI] Templ files generated"

  build:cosmes:
    dir: packages/cosmes
    preconditions:
      - sh: command -v pnpm
    sources:
      - "**/*.ts"
      - "**/*.js"
    generates:
      - dist
    deps:
      - task: install:cosmes
    cmds:
      - gum spin --spinner dot --title "Generating Chain Registry..." -- pnpm run gen:registry
      - gum log --level info --time kitchen "[COSMES] Chain Registry generated"
      - gum spin --spinner dot --title "Generating Go from Templ..." -- pnpm run gen:protobufs
      - gum log --level info --time kitchen "[COSMES] Protobufs generated"
      - gum spin --spinner dot --title "Generating Go from Templ..." -- pnpm run build
      - gum log --level info --time kitchen "[COSMES] Packages built"

  build:shoelace:
    dir: packages/shoelace
    preconditions:
      - sh: command -v pnpm
    sources:
      - "**/*.ts"
      - "**/*.js"
    generates:
      - dist
      - cdn
    deps:
      - task: install:shoelace
    cmds:
      - gum spin --spinner dot --title "Minifying Icon Set..." -- pnpm run minify
      - gum log --level info --time kitchen "[SHOELACE] Compressed Icon Set"
      - gum spin --spinner dot --title "Building Web Components..." -- pnpm run build
      - gum log --level info --time kitchen "[SHOELACE] Web Components built"

  run:example:
    dir: example
    sources:
      - "**/*.templ"
      - "**/*.go"
    generates:
      - "**/_templ.go"
    cmds:
      - gum log --level info --time kitchen "[EXAMPLE] Running at http://localhost:8080"
      - go run ./main.go

  publish:cosmes:
    dir: packages/cosmes
    preconditions:
      - sh: command -v npm
    cmds:
      - npm publish

  publish:shoelace:
    dir: packages/shoelace
    preconditions:
      - sh: command -v npm
    cmds:
      - npm publish

  install:cosmes:
    dir: packages/cosmes
    preconditions:
      - sh: command -v pnpm
    sources:
      - package.json
    generates:
      - pnpm-lock.yaml
      - node_modules
    cmds:
      - pnpm install

  install:shoelace:
    dir: packages/shoelace
    preconditions:
      - sh: command -v pnpm
    sources:
      - package.json
    generates:
      - pnpm-lock.yaml
      - node_modules
    cmds:
      - pnpm install

  install:example:
    preconditions:
      - sh: command -v go
    cmds:
      - go install github.com/air-verse/air@latest
      - go mod tidy

  publish:
    cmds:
      - task: publish:cosmes
      - task: publish:shoelace
