#yaml-language-server: $schema=https://json.schemastore.org/taskfile
version: "3"
tasks:
  default:
    cmds:
      - task: gen
      - task: build

  build:
    cmds:
      - task: build:cosmes
      - task: build:shoelace

  publish:
    cmds:
      - task: publish:cosmes
      - task: publish:shoelace

  gen:templ:
    cmd: templ generate

  test:
    cmds:
      - go test -v ./...

  bump:
    cmds:
      - devbox run bump

  build:cosmes:
    dir: packages/cosmes
    cmds:
      - devbox run build

  build:shoelace:
    dir: packages/shoelace
    cmds:
      - devbox run build

  publish:cosmes:
    dir: packages/cosmes
    cmds:
      - devbox run publish

  publish:shoelace:
    dir: packages/shoelace
    cmds:
      - devbox run publish
