#yaml-language-server: $schema=https://json.schemastore.org/taskfile
version: "3"
tasks:
  default:
    cmds:
      - task: gen
      - task: build

  build:
    cmds:
      - task: build:cosmes
      - task: build:shoelace

  gen:
    cmds:
      - templ generate
    silent: true

  build:cosmes:
    internal: true
    dir: packages/cosmes
    cmds:
      - devbox run build

  build:shoelace:
    internal: true
    dir: packages/shoelace
    cmds:
      - devbox run build

  nebula:bump:
    dir: .
    internal: true
    cmds:
      - devbox run bump
      - git add .
      - git commit -m "(chore) update build version [skip ci]"
      - git push
