// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package themes

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func BaseTheme() templ.CSSClass {
	templ_7745c5c3_CSSBuilder := templruntime.GetBuilder()
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-transition-x-slow:1000ms;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-transition-slow:500ms;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-transition-medium:250ms;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-transition-fast:150ms;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-transition-x-fast:50ms;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-font-mono:SFMono-Regular, Consolas, 'Liberation Mono', Menlo, monospace;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-font-sans:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif,
    'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-font-serif:Georgia, 'Times New Roman', serif;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-font-size-2x-small:0.625rem; 
	--sl-font-size-x-small: 0.75rem; 
  --sl-font-size-small: 0.875rem; 
  --sl-font-size-medium: 1rem; /* 16px */
  --sl-font-size-large: 1.25rem; /* 20px */
  --sl-font-size-x-large: 1.5rem; /* 24px */
  --sl-font-size-2x-large: 2.25rem; /* 36px */
  --sl-font-size-3x-large: 3rem; /* 48px */
  --sl-font-size-4x-large: 4.5rem; /* 72px */
  --sl-font-weight-light: 300;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-font-weight-normal:400;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-font-weight-semibold:500;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-font-weight-bold:700;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-letter-spacing-denser:-0.03em;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-letter-spacing-dense:-0.015em;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-letter-spacing-normal:normal;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-letter-spacing-loose:0.075em;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-letter-spacing-looser:0.15em;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-line-height-denser:1;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-line-height-dense:1.5;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-line-height-normal:1.625;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-line-height-loose:1.75;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-line-height-looser:2;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-border-radius-small:0.3rem; /* 3px */
  --sl-border-radius-medium: 0.5rem; /* 4px */
  --sl-border-radius-large: 0.75rem; /* 8px */
  --sl-border-radius-x-large: 1rem; /* 16px */
  --sl-border-radius-circle: 50%;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-border-radius-pill:9999px;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-spacing-3x-small:0.125rem; /* 2px */
  --sl-spacing-2x-small: 0.25rem; /* 4px */
  --sl-spacing-x-small: 0.5rem; /* 8px */
  --sl-spacing-small: 0.75rem; /* 12px */
  --sl-spacing-medium: 1rem; /* 16px */
  --sl-spacing-large: 1.25rem; /* 20px */
  --sl-spacing-x-large: 1.75rem; /* 28px */
  --sl-spacing-2x-large: 2.25rem; /* 36px */
  --sl-spacing-3x-large: 3rem; /* 48px */
  --sl-spacing-4x-large: 4.5rem; /* 72px */
  --sl-z-index-drawer: 700;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-z-index-dialog:800;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-z-index-dropdown:900;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-z-index-toast:950;`)
	templ_7745c5c3_CSSBuilder.WriteString(`--sl-z-index-tooltip:1000;`)
	templ_7745c5c3_CSSID := templ.CSSID(`BaseTheme`, templ_7745c5c3_CSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templ_7745c5c3_CSSID,
		Class: templ.SafeCSS(`.` + templ_7745c5c3_CSSID + `{` + templ_7745c5c3_CSSBuilder.String() + `}`),
	}
}

var _ = templruntime.GeneratedTemplate
